--- #YAML:1.0
name:                Weed
version:             0.0022
abstract:            Contains the Abstract that will be displayed on CPAN
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    base:                          0
    Benchmark:                     0
    Carp:                          0
    Class::ISA:                    0
    Math:                          0
    Math::Complex:                 0
    package:                       0
    Scalar::Util:                  0
    Test::More:                    0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Holger Seelig <holger.seelig@yahoo.de>
