#!/usr/bin/perl -w
use Test::More no_plan;
use strict;
use warnings;

BEGIN {
	$| = 1;
	chdir 't' if -d 't';
	unshift @INC, '../lib';
	#use_ok 'Weed';
}

use Weed;
ok my $proto1 = new X3DPrototype;

__END__
