#!/usr/freeware/bin/perl -w
#0.963u 0.147s 0:01.22 90.1% 0+0k 0+0io 0pf+0w

use lib "/net/people/holger/perl";
use strict;

use VRML;

my $vrml = '
PROTO Button [
  exposedField  SFBool   enabled	TRUE
  eventOut      SFBool   isActive	
  eventOut      SFBool   isOver	
  eventOut      SFBool   isOut	
  eventOut      SFTime   touchTime	
  eventOut      SFTime   downTime	
  eventOut      SFTime   overTime	
  eventOut      SFTime   outTime	
  eventOut      SFVec3f  distance_changed	
  exposedField  MFNode   children	[ ]
]
{
  Group {
  }
}

DEF Script Script { 
	eventIn SFBool	bool
	field	SFString	string	"äöüabc"
	field	SFVec3f	vec3f	1 2 3
	field	SFImage	image	1 1 3	0
	field	SFNode	self	USE Script
	field	SFColor	color	0 0 1
	url "vrmlscript:
function dummy (value, time) {
	string = \"\";
}
	"
	directOutput TRUE
	mustEvaluate FALSE
}
Script { 
}
Transform {
	translation 0 0 0
	rotation 0 0 1 0
	children []
}
Transform {
	translation 0 1 0
	rotation 0 0 1 1
}
';

my $nodes = Browser->createVrmlFromString($vrml);
#print $nodes;
#print "\nEOT\n";
print Browser;

1;
__END__

  url "
function dummy (value, time) {
	string = \"\";
}
  "
